on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: '3.6'}

    steps:
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - name: foo
        run: |
          if (.Platform$OS.type == "windows") {
            makevars_user <- path.expand("~/.R/Makevars")
            dir.create(dirname(makevars_user), recursive = TRUE)
            cat(file = makevars_user, append = TRUE,
            "CXX14=g++
            CXX14STD=-std=c++1y
            CXX14FLAGS=-Wall -g -O2")
          }
        shell: Rscript {0}

      - run: install.packages("xgboost")
        shell: Rscript {0}
