name: CI

on: [push]

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install System Dependencies
        uses: docker://rstudio/r-base:3.6-xenial
        env:
          R_LIBS_USER: ~/R/library
        run: ls .
